### ISSUE TITLE
Does it work with sketch 3.4?

### ISSUE THREAD

**Issue by pixtur** [wonderbit/sketch-select-similar-layers#1]
I like the idea of this plugin but it doesn't seem to work with Sketch v3.4. I'm not sure if this is related to the latest version, though.

**Comment by wonderbit** [comment]
Hi, yes it works with Sketch 3.4. Maybe it isn't working for you because there's a conflict of shortcuts (probably with the sketch measure plugin). I changed the shortcuts this morning to use ctrl+alt instead of ctrl+shift.

Please let me know if that fixes your problem!

**Comment by kinkou** [comment]
It doesn't work for me. Here's the messages that I see in the Console app when I try to select layers with the same fill color, depending on document:

In the file with lots of folders and symbols:

``` cocoascript
Nov 14 18:59:13 [edited] Sketch[63600]: Exception: TypeError: undefined is not a function (evaluating 'layer.style()')
Nov 14 18:59:13 [edited] Fill Color (Sketch Plugin)[63600]: TypeError: undefined is not a function (evaluating 'layer.style()')
    line: 101
    sourceURL: [edited]/Library/Containers/com.bohemiancoding.sketch3/Data/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Select Similar Objects.sketchplugin/Contents/Sketch/script.cocoascript
    column: 16
```

In the newly created document without an artboard:

``` cocoascript
Nov 14 19:05:59 [edited] Sketch[63600]: Exception: TypeError: null is not an object (evaluating 'artboard.layers')
Nov 14 19:05:59 [edited] Fill Color (Sketch Plugin)[63600]: TypeError: null is not an object (evaluating 'artboard.layers')
    line: 210
    sourceURL: [edited]/Library/Containers/com.bohemiancoding.sketch3/Data/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Select Similar Objects.sketchplugin/Contents/Sketch/script.cocoascript
    column: 31
```

And then when I add artboard, there's no messages, it simply doesn't select similar layers.

I'm using version 3.4 (15575)

**Comment by dmitryUX** [comment]
I'm also having problems with this plugin. 
Using sketch v3.4.2. 

> Maybe it isn't working for you because there's a conflict of shortcuts

It is not about shortcuts, because I'm trying to use the plugin via the menu controls - same effect, nothing happens. 

P.S. The description of the plugin sounds like a really great time saver for some of us, who likes to create gigantic boards - please fix :)

**Comment by wonderbit** [comment]
I believe I have found the problem, and it should now be fixed for good.

The thing is I wasn't handling slices properly, and sometimes the plugin would check for the fill or border of a slice and result in an error.

Thank you @pixtur and @dmitryUX for the heads-up! And thanks @kinkou for the console logs! Very helpful.

**Comment by kinkou** [comment]
Great, Wessley, thank you. I'm ready to test as soon as the new version is out )

**Comment by renatocarvalho** [comment]
I just tried to select layers with the same border color or same border width and none of them worked. Using Sketch Version 3.4.4 (17249)

**Comment by wonderbit** [comment]
@renatocarvalho Mmmm… Could you try again and if still failing, open Console.app and find any log messages that start with "Sketch:" and/or "Fill Color (Sketch Plugin)", "Border Color (Sketch Plugin)", etc.

Thanks!

**Comment by dchatham** [comment]
I think people might be expecting it to work across multiple art-board.  It currently works fine on a single page. To be super useful, it would be at least multiple artboards within a single page, or global, multi-arboard and multi-page.

I was able to hack this and make it work by dragging a color off the artboard, into the gutter, then use the tool!  

See here...
https://www.evernote.com/l/ABaXkyh3Wh5OOb432b1CvZsR6oc9u6AaU4k

**Comment by wonderbit** [comment]
@dchatham Actually, you just need to edit the file in "Select Similar Layers.sketchplugin/Contents/Sketch/script.cocoascript" and set the **selectInAllArtboards** variable to true.

I don't think we can do multiple pages though…

**Comment by kastrom** [comment]
Hey @wonderbit, Love the idea of this, but I'm not able to get this working on Sketch 3.8 — is it compatible with the latest version yet?
